// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCciUlceDOsD-ljX2ROMXj4_zKqWap3ySw',
    appId: '1:188508332189:web:0d3b06c38174596b557474',
    messagingSenderId: '188508332189',
    projectId: 'flyer-project-2b5c9',
    authDomain: 'flyer-project-2b5c9.firebaseapp.com',
    storageBucket: 'flyer-project-2b5c9.firebasestorage.app',
    measurementId: 'G-1J3SSEMD1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0awSU2uj1aP_j-fcTQfPGoUb-BDrbwAw',
    appId: '1:188508332189:android:dcf2f57cd66e13f9557474',
    messagingSenderId: '188508332189',
    projectId: 'flyer-project-2b5c9',
    storageBucket: 'flyer-project-2b5c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsKzTdigpgMSw9XbuMCpnYB4d6DWjbEjY',
    appId: '1:188508332189:ios:3d947e6b82b3887c557474',
    messagingSenderId: '188508332189',
    projectId: 'flyer-project-2b5c9',
    storageBucket: 'flyer-project-2b5c9.firebasestorage.app',
    iosBundleId: 'com.example.flyerDisplayApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsKzTdigpgMSw9XbuMCpnYB4d6DWjbEjY',
    appId: '1:188508332189:ios:3d947e6b82b3887c557474',
    messagingSenderId: '188508332189',
    projectId: 'flyer-project-2b5c9',
    storageBucket: 'flyer-project-2b5c9.firebasestorage.app',
    iosBundleId: 'com.example.flyerDisplayApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCciUlceDOsD-ljX2ROMXj4_zKqWap3ySw',
    appId: '1:188508332189:web:05ea1d6cece3d86c557474',
    messagingSenderId: '188508332189',
    projectId: 'flyer-project-2b5c9',
    authDomain: 'flyer-project-2b5c9.firebaseapp.com',
    storageBucket: 'flyer-project-2b5c9.firebasestorage.app',
    measurementId: 'G-QC3MFEV36Y',
  );
}
